///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace JenkinsTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the JenkinsTest1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("02ae0d2e-c915-4192-8c7b-2499ed95e08a")]
    public partial class JenkinsTest1Repository : RepoGenBaseFolder
    {
        static JenkinsTest1Repository instance = new JenkinsTest1Repository();
        JenkinsTest1RepositoryFolders.KeyPromptFormAppFolder _keypromptform;
        JenkinsTest1RepositoryFolders.KeePassAppFolder _keepass;
        JenkinsTest1RepositoryFolders.MainFormAppFolder _mainform;
        JenkinsTest1RepositoryFolders.PwEntryFormAppFolder _pwentryform;

        /// <summary>
        /// Gets the singleton class instance representing the JenkinsTest1Repository element repository.
        /// </summary>
        [RepositoryFolder("02ae0d2e-c915-4192-8c7b-2499ed95e08a")]
        public static JenkinsTest1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public JenkinsTest1Repository() 
            : base("JenkinsTest1Repository", "/", null, 0, false, "02ae0d2e-c915-4192-8c7b-2499ed95e08a", ".\\RepositoryImages\\JenkinsTest1Repository02ae0d2e.rximgres")
        {
            _keypromptform = new JenkinsTest1RepositoryFolders.KeyPromptFormAppFolder(this);
            _keepass = new JenkinsTest1RepositoryFolders.KeePassAppFolder(this);
            _mainform = new JenkinsTest1RepositoryFolders.MainFormAppFolder(this);
            _pwentryform = new JenkinsTest1RepositoryFolders.PwEntryFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("02ae0d2e-c915-4192-8c7b-2499ed95e08a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The KeyPromptForm folder.
        /// </summary>
        [RepositoryFolder("21d36824-ea9a-4c39-8927-6676fd2942d3")]
        public virtual JenkinsTest1RepositoryFolders.KeyPromptFormAppFolder KeyPromptForm
        {
            get { return _keypromptform; }
        }

        /// <summary>
        /// The KeePass folder.
        /// </summary>
        [RepositoryFolder("06785340-03f4-47a5-97e3-0c542677e6af")]
        public virtual JenkinsTest1RepositoryFolders.KeePassAppFolder KeePass
        {
            get { return _keepass; }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("f8341065-a404-443b-acd6-c7ba00ea58ba")]
        public virtual JenkinsTest1RepositoryFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }

        /// <summary>
        /// The PwEntryForm folder.
        /// </summary>
        [RepositoryFolder("120e1c7c-85f0-4c66-b760-c3bcafd7a749")]
        public virtual JenkinsTest1RepositoryFolders.PwEntryFormAppFolder PwEntryForm
        {
            get { return _pwentryform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class JenkinsTest1RepositoryFolders
    {
        /// <summary>
        /// The KeyPromptFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("21d36824-ea9a-4c39-8927-6676fd2942d3")]
        public partial class KeyPromptFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;
            RepoItemInfo _mbtnokInfo;

            /// <summary>
            /// Creates a new KeyPromptForm  folder.
            /// </summary>
            public KeyPromptFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeyPromptForm", "/form[@controlname='KeyPromptForm']", parentFolder, 30000, null, true, "21d36824-ea9a-4c39-8927-6676fd2942d3", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", "?/?/text[@accessiblerole='Text']", 30000, null, "44f8481a-d1a1-4aef-a667-05173fa85359");
                _mbtnokInfo = new RepoItemInfo(this, "MBtnOK", "button[@controlname='m_btnOK']", 30000, null, "51b7afb3-89c6-43b0-8baf-ecd16da2202f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("21d36824-ea9a-4c39-8927-6676fd2942d3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("21d36824-ea9a-4c39-8927-6676fd2942d3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("44f8481a-d1a1-4aef-a667-05173fa85359")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("44f8481a-d1a1-4aef-a667-05173fa85359")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The MBtnOK item.
            /// </summary>
            [RepositoryItem("51b7afb3-89c6-43b0-8baf-ecd16da2202f")]
            public virtual Ranorex.Button MBtnOK
            {
                get
                {
                    return _mbtnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnOK item info.
            /// </summary>
            [RepositoryItemInfo("51b7afb3-89c6-43b0-8baf-ecd16da2202f")]
            public virtual RepoItemInfo MBtnOKInfo
            {
                get
                {
                    return _mbtnokInfo;
                }
            }
        }

        /// <summary>
        /// The KeePassAppFolder folder.
        /// </summary>
        [RepositoryFolder("06785340-03f4-47a5-97e3-0c542677e6af")]
        public partial class KeePassAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new KeePass  folder.
            /// </summary>
            public KeePassAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeePass", "/form[@title='KeePass']", parentFolder, 30000, null, true, "06785340-03f4-47a5-97e3-0c542677e6af", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", 30000, null, "c4ce5f62-d98c-482f-badd-7226322d7617");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("06785340-03f4-47a5-97e3-0c542677e6af")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("06785340-03f4-47a5-97e3-0c542677e6af")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("c4ce5f62-d98c-482f-badd-7226322d7617")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("c4ce5f62-d98c-482f-badd-7226322d7617")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("f8341065-a404-443b-acd6-c7ba00ea58ba")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addentryInfo;
            RepoItemInfo _msmithInfo;
            RepoItemInfo _saveInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "f8341065-a404-443b-acd6-c7ba00ea58ba", "")
            {
                _addentryInfo = new RepoItemInfo(this, "AddEntry", "?/?/button[@accessiblename='Add Entry']", 30000, null, "bd297bf1-8c15-4256-b0b9-dbd3188f9881");
                _msmithInfo = new RepoItemInfo(this, "Msmith", "container[@controlname='m_splitHorizontal']/?/?/container[@controlname='m_splitVertical']/?/?/table[@controlname='m_lvEntries']/?/?/cell[@text='msmith']", 30000, null, "fb76e61b-2a52-4cc6-a054-c7a6e86b7981");
                _saveInfo = new RepoItemInfo(this, "Save", "?/?/button[@accessiblename='Save']", 30000, null, "bab8a2e5-4a7c-4e40-ac3a-c2d539be6eb5");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "7f166995-7b18-4a29-ad2d-04d3c9e24fb7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f8341065-a404-443b-acd6-c7ba00ea58ba")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f8341065-a404-443b-acd6-c7ba00ea58ba")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddEntry item.
            /// </summary>
            [RepositoryItem("bd297bf1-8c15-4256-b0b9-dbd3188f9881")]
            public virtual Ranorex.Button AddEntry
            {
                get
                {
                    return _addentryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddEntry item info.
            /// </summary>
            [RepositoryItemInfo("bd297bf1-8c15-4256-b0b9-dbd3188f9881")]
            public virtual RepoItemInfo AddEntryInfo
            {
                get
                {
                    return _addentryInfo;
                }
            }

            /// <summary>
            /// The Msmith item.
            /// </summary>
            [RepositoryItem("fb76e61b-2a52-4cc6-a054-c7a6e86b7981")]
            public virtual Ranorex.Cell Msmith
            {
                get
                {
                    return _msmithInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Msmith item info.
            /// </summary>
            [RepositoryItemInfo("fb76e61b-2a52-4cc6-a054-c7a6e86b7981")]
            public virtual RepoItemInfo MsmithInfo
            {
                get
                {
                    return _msmithInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("bab8a2e5-4a7c-4e40-ac3a-c2d539be6eb5")]
            public virtual Ranorex.Button Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("bab8a2e5-4a7c-4e40-ac3a-c2d539be6eb5")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("7f166995-7b18-4a29-ad2d-04d3c9e24fb7")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("7f166995-7b18-4a29-ad2d-04d3c9e24fb7")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The PwEntryFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("120e1c7c-85f0-4c66-b760-c3bcafd7a749")]
        public partial class PwEntryFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _mbtnokInfo;

            /// <summary>
            /// Creates a new PwEntryForm  folder.
            /// </summary>
            public PwEntryFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PwEntryForm", "/form[@controlname='PwEntryForm']", parentFolder, 30000, null, true, "120e1c7c-85f0-4c66-b760-c3bcafd7a749", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", "?/?/tabpage[@controlname='m_tabEntry']/text[@controlname='m_tbTitle']/text[@accessiblerole='Text']", 30000, null, "260f1685-b426-4f17-9add-77457744cd0f");
                _usernameInfo = new RepoItemInfo(this, "UserName", "?/?/tabpage[@controlname='m_tabEntry']/?/?/text[@accessiblename='User name:']", 30000, null, "22c1bd5e-2386-46be-bc5d-9c05c24fa5f5");
                _mbtnokInfo = new RepoItemInfo(this, "MBtnOK", "button[@controlname='m_btnOK']", 30000, null, "f18da73b-2f38-4f7b-927b-f606e8d2d665");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("120e1c7c-85f0-4c66-b760-c3bcafd7a749")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("120e1c7c-85f0-4c66-b760-c3bcafd7a749")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("260f1685-b426-4f17-9add-77457744cd0f")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("260f1685-b426-4f17-9add-77457744cd0f")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("22c1bd5e-2386-46be-bc5d-9c05c24fa5f5")]
            public virtual Ranorex.Text UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("22c1bd5e-2386-46be-bc5d-9c05c24fa5f5")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The MBtnOK item.
            /// </summary>
            [RepositoryItem("f18da73b-2f38-4f7b-927b-f606e8d2d665")]
            public virtual Ranorex.Button MBtnOK
            {
                get
                {
                    return _mbtnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnOK item info.
            /// </summary>
            [RepositoryItemInfo("f18da73b-2f38-4f7b-927b-f606e8d2d665")]
            public virtual RepoItemInfo MBtnOKInfo
            {
                get
                {
                    return _mbtnokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}